name: Build Dune Legacy

on:
  push:
    branches: [ main, release-* ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      
      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
      
      - name: Build
        run: cmake --build build --config Release
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DuneLegacy-Windows
          path: |
            build/bin/Release/dunelegacy.exe
            build/bin/Release/*.dll

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      
      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
      
      - name: Build
        run: cmake --build build --config Release
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DuneLegacy-macOS
          path: build/bin/dunelegacy

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      
      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
      
      - name: Build
        run: cmake --build build --config Release
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DuneLegacy-Linux
          path: build/bin/dunelegacy

